#!/bin/sh /etc/rc.common

START=99
STOP=10

NAME="opencode"
PROG="$(find /usr/sbin/ -maxdepth 1 -name "${NAME}*" | head -1)"

log() {
	# echo "$(date "+%Y.%m.%d_%H%M%S") - ${1}" >>/tmp/$NAME.log
	logger -t ${NAME} "${1}"
}

start() {
	config_load "$NAME"
	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1
	local port username password
	config_get port "config" "port" "4096"
	config_get username "config" "username" "opencode"
	config_get password "config" "password"
	# 创建配置目录
	[[ -n "${username}" ]] && export OPENCODE_SERVER_USERNAME="$username"
	[[ -n "${password}" ]] && export OPENCODE_SERVER_PASSWORD="$password"
	# 构建启动参数
	start-stop-daemon -S -q -b -x "$PROG" -- web --hostname 0.0.0.0 --port ${port}
	log "${NAME} Starting ..."
}

stop() {
	# kill -9 $(pgrep -f "${PROG}*" | sed "s/$$//g") 2>/dev/null
	start-stop-daemon -K -q -s KILL -x "$PROG" 2>/dev/null
	log "${NAME} stopped ..."
}