#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@napcatapi[-1]
	add ucitrack napcatapi
	set ucitrack.@napcatapi[-1].init=napcatapi
	commit ucitrack
EOF

rm -rf /tmp/luci-* /tmp/rpcd/*
# 重启 UCITrack 服务
# /etc/init.d/ucitrack restart >/dev/null 2>&1
exit 0