name: GitHUB Actions Erase Commits
on:
  repository_dispatch:
  workflow_dispatch:      
    inputs:
      repos:
        description: "Select the Repositories"
        required: false
        default: "all"
        type: choice
        options:
          - 3wlh.github.io


jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id || github.event.sender.id == '119362912'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    
    - name: Set Git identity
      run : |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Git Clone Repositories
      run : |
        test -d "GitHub" || mkdir -p "GitHub" 
        cd GitHub && ls
        git clone https://3wlh:${{ secrets.TOKEN_3WLH }}@github.com/3wlh/${{ inputs.repos }}
        cd 3wlh.github.io && ls
        rm -rf ADB.txt
        git add .
        git commit -m "update Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f