name: Actions Package SDK

on:
  workflow_call:
    inputs:
      cache:
        description: |
          是否清理缓存?
        required: false
        default: false
        type: boolean
      
      feeds:
        description: |
          是否禁用feeds?
        required: false
        default: false
        type: boolean  
      
      out:
        description: |
          是否详细输出?
        required: false
        default: true
        type: boolean
      
      sdk:
        description: |
          选择编译插件
        required: false
        type: string
        
      package:
        description: |
          选择编译插件
        required: false
        type: string

          
jobs:
  jod_initial:
    name: Actions Build ${{ inputs.package }}
    runs-on: ubuntu-latest
    outputs:
      time: ${{steps.output_time.outputs.time}}
    steps: 
      - name: output Time
        id: output_time
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT
          
      - name: Delete GitHub Release
        uses: dev-drprasad/delete-tag-and-release@master
        with:
          tag_name: GitHub-Actions_${{ inputs.package }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Cleanup GitHub Cache
        if: (inputs.cache == true)
        run: |
          gh cache delete --all --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        
  jobs_build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk_version }}
    needs: jod_initial
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        sdk_version:
          - openwrt-24.10
          #- SNAPSHOT
    env:
      BUILD_TIME: ${{ needs.jod_initial.outputs.time }}
      COMPRESSED_FILENAME: ${{ inputs.package }}-${{ matrix.sdk_version }}-${{ matrix.arch }}_${{ needs.jod_initial.outputs.time }}.tar.gz
      OUTPUT_DIR: ${{ inputs.package }}/Output/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set Environment Variables
        run: |
          if [ "${{ inputs.out }}" == "true" ]; then
            echo "Buildout=sc" >> $GITHUB_ENV
          fi
          if [[ "${{ inputs.feeds }}" == "true"  || "${{ inputs.package }}" =~ "static" ]]; then
            echo "feeds=true" >> $GITHUB_ENV
          fi

      - name: Build Openwrt Packages
        if: inputs.sdk == 'Openwrt'
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk_version }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ inputs.package }}
          NO_DEFAULT_FEEDS: ${{ env.feeds }}
          NO_REFRESH_CHECK: true
          V: ${{ env.Buildout }}

      - name: Build Immortalwrt Packages
        if: inputs.sdk == 'Immortalwrt'
        uses: immortalwrt/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk_version }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ inputs.package }}
          NO_DEFAULT_FEEDS: ${{ env.feeds }}
          NO_REFRESH_CHECK: true
          V: ${{ env.Buildout }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk_version }}
          path: |
            bin/packages/${{ matrix.arch }}/packages_ci/*.[ia]pk
            bin/packages/riscv64_generic/packages_ci/*.[ia]pk

      - name: Create compress files
        id: compress_files
        continue-on-error: true
        run: |
          test -d ${{ env.OUTPUT_DIR }} || mkdir -p ${{ env.OUTPUT_DIR }}
          if [ "${{ matrix.arch }}" = "riscv64_riscv64" ] && [ "${{ matrix.sdk_version }}" = "SNAPSHOT" ]; then
            TARGET_PATH="bin/packages/riscv64_generic/packages_ci"
          else
            TARGET_PATH="bin/packages/${{ matrix.arch }}/packages_ci"
          fi
          if [ -d "$TARGET_PATH" ] && [ "$(ls -A $TARGET_PATH)" ]; then
            # 只执行一次tar命令，保留文件结构
            tar -zcvf ${{ env.OUTPUT_DIR }}/${{ env.COMPRESSED_FILENAME }} -C $TARGET_PATH .
            echo "✅ 压缩文件成功：${{ env.OUTPUT_DIR }}/${{ env.COMPRESSED_FILENAME }}"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ 目标目录无文件：$TARGET_PATH"
            echo "status=failed" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload ${{ inputs.branch }} as release assets
        if: steps.files.outputs.status == 'success'
        uses: ncipollo/release-action@main
        with:
          tag: GitHub-Actions_${{ inputs.package }}
          name: ${{ inputs.package }}
          artifacts: ${{ env.OUTPUT_DIR }}/*
          body: |
            ## 编译信息
            - 编译时间：`${{ env.BUILD_TIME }}`
            - SDK版本：`${{ inputs.sdk }}`
            - 架构：`${{ matrix.arch }}`
            - 插件：`${{ inputs.package }}`
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}