name: Actions Build and Package

on:
  workflow_call:
    inputs:
      version:
        description: |
          选择 OpenWrt 版本
        required: false
        type: string
      
      package_name:
        description: |
          选择编译插件
        required: false
        type: string

env:
  PACKAGE_NAME: ${{ inputs.package_name }}
  CACHE_DIR: ~/.cache
  TZ: Asia/Shanghai
  Download_URL: "https://downloads.openwrt.org/releases/${{ inputs.Version }}/targets"
  UPLOAD_BIN_DIR: false

jobs:
  jod_initial:
    name: Actions Build ${{ inputs.package_name }}
    runs-on: ubuntu-latest
    outputs:
      time: ${{steps.output_time.outputs.time}}
    steps: 
      - name: output Time
        id: output_time
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT

  jod_build:
    name: Build - Architecture: ${{ matrix.arch }}
    needs: jod_initial
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_generic
            sdk_url_path: layerscape/armv8_64b
            sdk_name: '-sdk-.*-layerscape-armv8_64b_'
          - arch: x86_64
            sdk_url_path: x86/64
            sdk_name: '-sdk-.*-x86-64_'

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      BUILD_TIME: ${{ needs.jod_initial.outputs.time }}
      OUTPUT_DIR: ${{ github.workspace }}/Output/
      CONFIG_CCACHE: y
    steps: 
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: |
          # DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc

      - name: Setup Cache
        uses: actions/cache@main
        with:
          path: ${{ env.CACHE_DIR }}
          key: openwrt-${{ matrix.arch }}

      - name: Configure environment variables
        run: |
          test -d "${{ env.CACHE_DIR }}" || mkdir -pm 755 "${{ env.CACHE_DIR }}"

      - name: Download and Unzip SDK
        run: |
          cd "${{ env.CACHE_DIR }}"
          if [[ $(du -s "${{ env.CACHE_DIR }}" | awk '{ print $1}') -lt 10240 ]]; then
            echo -e "\e[1;32m Start downloading the SDK \e[0m"
            if ! ( wget -qO - "${Download_URL}/$SDK_URL_PATH/sha256sums" | grep -- "${{ env.SDK_NAME }}" > sha256sums.small 2>/dev/null ); then
              echo -e "\e[1;31m Error:Can not find ${{ env.SDK_NAME }} file in sha256sums. \e[0m"
              exit 1
            fi
            SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
              wget -qO "$SDK_FILE" "${Download_URL}/$SDK_URL_PATH/$SDK_FILE"
              if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
                echo -e "\e[1;31m Error:SDK can not be verified! \e[0m"
                exit 1
              fi
            fi
            tar -I zstd -xf "${SDK_FILE}" -C "${{ env.SDK_HOME }}" --strip=1 && rm -fr ${SDK_FILE}
          fi
          test -d "dl" && rm -rf "dl" || true
          test -d "feeds" && rm -rf "feeds" || true
          cp feeds.conf.default feeds.conf
          sed -i 's#git.openwrt.org/openwrt/openwrt#github.com/openwrt/openwrt#' feeds.conf
          sed -i 's#git.openwrt.org/feed/packages#github.com/openwrt/packages#' feeds.conf
          sed -i 's#git.openwrt.org/project/luci#github.com/openwrt/luci#' feeds.conf
          sed -i 's#git.openwrt.org/feed/telephony#github.com/openwrt/telephony#' feeds.conf
          echo "status=success" >> $GITHUB_OUTPUT
          
      - name: Update and Install Packages
        run: |
          cd "${{ env.CACHE_DIR }}"
          # ./scripts/feeds update -a >/dev/null 2>&1
          find "${{ github.workspace }}" -maxdepth 1 -exec ln -s {} "package/" \;
          rm package/$(basename ${{ github.workspace }})
          ./scripts/feeds install -a >/dev/null 2>&1
          cd -

      - name: Build Packages
        run: |
          cd "${{ env.SDK_HOME }}"
          make defconfig  >/dev/null
          make package/${{ env.PACKAGE_NAME }}/{clean,compile} V=s
          # make package/${{ env.PACKAGE_NAME }}/{clean,compile}
          find "${{ env.SDK_HOME }}/bin/" -type f -name "*.ipk" -exec ls -lh {} \;
          cd -

      - name: Copy Bin Files
        run: |
          touch release.txt
          echo "${{ env.PACKAGE_NAME }}" > release.txt
          # name=*$(echo ${{ env.PACKAGE_NAME }} | cut -d "-" -f 3-)*.ipk
          name="*$(echo ${{ env.PACKAGE_NAME }} | sed 's/luci-app-//')*.ipk"
          PACKAGE_DIR="${{ env.SDK_HOME }}/bin/"
          File=$(find "${PACKAGE_DIR}" -name "${name}")
          for dir in $(echo ${File} | sed 's| | |g')
          do
            echo ${dir}
            cp -f ${dir} "${{ env.IPK_DIR }}/$(basename ${dir} | sed 's/_all//' | sed "s/.ipk/_${{ matrix.arch }}.ipk/")"
          done
          find "${{ env.IPK_DIR }}" -name "*.ipk" -exec ls -lh {} \;

      - name: Upload to bin directory
        uses: actions/upload-artifact@main
        if: ${{env.UPLOAD_BIN_DIR}} == 'true'
        with:
          name: ${{ matrix.arch }}_package_${{ env.Time }}
          path: ${{ env.SDK_HOME }}/bin 

      - name: Upload to Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.Time }}
          body_path: release.txt
          files: ${{ env.IPK_DIR }}/*.ipk