name: Build Packages

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      package_name:
        description: |
          选择编译插件
        required: false
        default: "all"
        type: choice
        options:
          - all
          - luci-app-cifs2-mount
          - luci-app-bypass
          - luci-app-unishare
          - luci-app-v2ray-server
          - luci-app-sunpanel
          - sunpanel

jobs:
  jod_time:
    name: Acquisition Time
    runs-on: ubuntu-latest
    outputs:
      time: ${{steps.output_time.outputs.time}}
    steps: 
      - name: output Time
        id: output_time
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT


  jobs_build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    needs: jod_time
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        sdk:
          - openwrt-24.10
          - SNAPSHOT
    env:
      Time: ${{ needs.jod_time.outputs.time }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ inputs.package_name }}
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: |
            bin/packages/${{ matrix.arch }}/packages_ci/*.apk
            bin/packages/riscv64_generic/packages_ci/*.apk
            bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Create compress files
        continue-on-error: true
        run: |
          if [ "${{ matrix.arch }}" = "riscv64_riscv64" ] && [ "${{ matrix.sdk }}" = "SNAPSHOT" ]; then
            tar -zcvf ${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/riscv64_generic/ packages_ci
          else
            tar -zcvf ${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci
          fi
          
      - name: Upload to Release packages
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ inputs.package_name }}
          tag_name: ${{ env.Time }}
          body: ${{ inputs.package_name }}
          files: "${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz"