name: Call SDK Download

on:
  workflow_call:
    inputs:
      cache:
        description: |
          是否清理缓存?
        required: false
        default: false
        type: boolean
      
      feeds:
        description: |
          是否禁用feeds?
        required: false
        default: false
        type: boolean  
      
      out:
        description: |
          是否详细输出?
        required: false
        default: true
        type: boolean
      
      sdk:
        description: |
          选择编译插件
        required: false
        type: string
        
      package:
        description: |
          选择编译插件
        required: false
        type: string
      
      version:
          description: |
            选择 OpenWrt 版本
          required: false
          type: string

env:
  PACKAGE_NAME: ${{ inputs.package }}
  CACHE_DIR: /tmp/.cache
  TZ: Asia/Shanghai
  Download_URL: "https://downloads.openwrt.org/releases/${{ inputs.Version }}.0/targets"
  UPLOAD_BIN_DIR: false

jobs:
  jod_initial:
    name: Actions Build ${{ inputs.package }}
    runs-on: ubuntu-latest
    outputs:
      time: ${{steps.output_time.outputs.time}}
    steps: 
      - name: output Time
        id: output_time
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT
        
      - name: Delete GitHub Release
        uses: dev-drprasad/delete-tag-and-release@master
        with:
          tag_name: GitHub-Actions_${{ inputs.package }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        
      - name: Cleanup GitHub Cache
        if: (inputs.cache == true)
        run: |
          gh cache delete --all --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
               
  jod_build:
    name: Build Architecture ${{ matrix.arch }}
    needs: jod_initial
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_generic
            sdk_url_path: layerscape/armv8_64b
            sdk_name: '-sdk-.*-layerscape-armv8_64b_'
          - arch: x86_64
            sdk_url_path: x86/64
            sdk_name: '-sdk-.*-x86-64_'

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      BUILD_TIME: ${{ needs.jod_initial.outputs.time }}
      OUTPUT_DIR: ${{ github.workspace }}/Output
      COMPRESSED_FILENAME: ${{ inputs.package }}-${{ inputs.version }}-${{ matrix.arch }}_${{ needs.jod_initial.outputs.time }}.tar.gz
      
    steps: 
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc

      - name: Setup Cache
        uses: actions/cache@main
        with:
          path: ${{ env.CACHE_DIR }}
          key: openwrt-${{ matrix.arch }}

      - name: Configure environment variables
        run: |
          test -d "${{ env.CACHE_DIR }}" || mkdir -pm 755 "${{ env.CACHE_DIR }}"
          test -d "${{ env.OUTPUT_DIR }}" || mkdir -pm 755 "${{ env.OUTPUT_DIR }}"
          if [ "${{ inputs.out }}" == "true" ]; then
            echo "Buildout=v" >> $GITHUB_ENV
          fi

      - name: Download and Unzip SDK
        run: |
          cd "${{ env.CACHE_DIR }}"
          if [[ $(du -s "${{ env.CACHE_DIR }}" | awk '{ print $1}') -lt 10240 ]]; then
            echo -e "\e[1;32m ✅ 开始下载 SDK \e[0m"
            if ! ( wget -qO - "${Download_URL}/$SDK_URL_PATH/sha256sums" | grep -- "${{ env.SDK_NAME }}" > sha256sums.small 2>/dev/null ); then
              echo -e "\e[1;31m  ❌ 错误：在 sha256sums 中找不到 ${{ env.SDK_NAME }} 文件. \e[0m"
              exit 1
            fi
            SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
              echo -e "\e[1;32m ✅ 下载url:${Download_URL}/$SDK_URL_PATH/$SDK_FILE \e[0m"
              wget -qO "$SDK_FILE" "${Download_URL}/$SDK_URL_PATH/$SDK_FILE"
              if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
                echo -e "\e[1;31m ❌ 错误：无法验证SDK！ \e[0m"
                exit 1
              fi
            fi
            echo -e "\e[1;32m ✅ 解压文件:$SDK_FILE \e[0m"
            tar -I zstd -xf "${SDK_FILE}" -C "${{ env.CACHE_DIR }}" --strip=1 && rm -fr ${SDK_FILE}
            ls
          fi
          test -d "dl" && rm -rf "dl" || true
          test -d "feeds" && rm -rf "feeds" || true
          cp feeds.conf.default feeds.conf
          sed -i 's,git.openwrt.org/openwrt/openwrt/,github.com/openwrt/openwrt/,' feeds.conf
          sed -i 's,git.openwrt.org/feed/packages/,github.com/openwrt/packages/,' feeds.conf
          sed -i 's,git.openwrt.org/project/luci/,github.com/openwrt/luci/,' feeds.conf
          sed -i 's,git.openwrt.org/feed/telephony/,github.com/openwrt/telephony/,' feeds.conf
          echo "status=success" >> $GITHUB_OUTPUT
          
      - name: Update and Install Packages
        run: |
          cd "${{ env.CACHE_DIR }}"
          # ./scripts/feeds update -a >/dev/null 2>&1
          find "${{ github.workspace }}" -maxdepth 1 -exec ln -s {} "package/" \;
          # rm package/$(basename ${{ github.workspace }})
          ./scripts/feeds install -a >/dev/null 2>&1
          cd -

      - name: Build Packages
        run: |
          cd "${{ env.CACHE_DIR }}"
          make defconfig  >/dev/null
          make package/${{ env.PACKAGE_NAME }}/{clean,compile} V=${{ env.Buildout }} CONFIG_AUTOREMOVE=y 
          # make package/${{ env.PACKAGE_NAME }}/{clean,compile} 
          find "${{ env.CACHE_DIR }}/bin/" -type f -name "*.[ai]pk" -exec ls -lh {} \;
          cd -

      - name: Create compress files
        id: compress_files
        run: |
          # name=*$(echo ${{ env.PACKAGE_NAME }} | cut -d "-" -f 3-)*.ipk
          # name="*$(echo ${{ env.PACKAGE_NAME }} | sed 's/luci-app-//')*.ipk"
          PACKAGE_DIR="${{ env.CACHE_DIR }}/bin/packages/"
          File=$(find "${PACKAGE_DIR}/" -name "*${{ env.PACKAGE_NAME }}*.[ai]pk")
          echo 目录:${dir}
          for dir in $(echo ${File} | sed 's| | |g')
          do
            echo "✅ 文件目录:$(dirname ${dir})"
            TARGET_PATH="$(dirname ${dir})"
          done
          if [ -d "$TARGET_PATH" ] && [ "$(ls -A $TARGET_PATH)" ]; then
            # 只执行一次tar命令，保留文件结构
            tar -zcf ${{ env.OUTPUT_DIR }}/${{ env.COMPRESSED_FILENAME }} -C $TARGET_PATH .
            echo "✅ 压缩文件成功：${{ env.OUTPUT_DIR }}/${{ env.COMPRESSED_FILENAME }}"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ 目标目录无文件：$TARGET_PATH"
            echo "status=failed" >> $GITHUB_OUTPUT
          fi
          tar -zcf ${{ env.OUTPUT_DIR }}/${{ env.COMPRESSED_FILENAME }} -C $TARGET_PATH .
          find "${{ env.OUTPUT_DIR }}" -name "*.gz" -exec ls -lh {} \;

      - name: Upload to bin directory
        uses: actions/upload-artifact@main
        if: ${{ env.UPLOAD_BIN_DIR == 'true' }} 
        with:
          name: ${{ matrix.arch }}_package_${{ env.Time }}
          path: ${{ env.CACHE_DIR }}/bin 

      - name: Upload as release assets
        if: steps.compress_files.outputs.status == 'success'
        uses: ncipollo/release-action@main
        with:
          tag: GitHub-Actions_${{ inputs.package }}
          name: ${{ inputs.package }}
          artifacts: ${{ env.OUTPUT_DIR }}/*
          body: |
            ## 编译信息
            - 编译时间：`${{ env.BUILD_TIME }}`
            - SDK版本：`${{ inputs.sdk }}`
            - 插件：`${{ inputs.package }}`
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}