name: Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: false
        type: boolean
      
      package_name:
        description: "Select the package"
        required: false
        default: "all"
        type: choice
        options:
          - all

env:
  PACKAGE_NAME: ${{ inputs.package_name }}
  CACHE_DIR: ~/cache
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: true

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: Test-0
            delayed: "0"
          - arch: Test-1
            delayed: "5"

    env:
      Delayed: ${{ matrix.delayed }}
      CCACHE_DIR: ~/.ccache
      CONFIG_CCACHE: y
    steps: 
      - name: Checkout
        uses: actions/checkout@main
        
      - name: ADD to ENV
        run: |
          sleep ${{ env.Delayed }}
        
      - name: ADD to ENV
        run: |
          sudo timedatectl set-timezone "${TZ}"
          test ! -f "Time.env" && echo "Time=$(date +"%Y.%m.%d_%H%M%S")" > Time.env
          test -f "Time.env" && cat Time.env >> $GITHUB_ENV
          [ ${{ env.Time }} == "" ] && exit 1
          
      - name: Configuration
        run: |
          echo ${{ env.Time }}
          
      - name: SSH connection to Actions
        if: (inputs.ssh == true) || contains(github.event.action, 'ssh')
        uses: mxschmitt/action-tmate@v3  

  notify:
    name: Notify Release Publish
    runs-on: ubuntu-latest
    env:
      TRIGGER_URL: ${{ secrets.TRIGGER_URL }}
      TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
    needs: release
    steps:
      - name: Notify Jenkins
        run: |
          if [ -z "$TRIGGER_URL" ] ; then
            echo "::warning::No trigger url found, skip..."
            exit 0
          fi
          curl -X POST \
              -H "Content-Type: application/json; charset=utf-8" \
              -H "Authorization: Bearer $TRIGGER_TOKEN" \
              -d "{\"event\":\"release\",\"repository\":\"${{ github.repository }}\",\"ref\":\"${{ github.ref }}\"}" \
              "$TRIGGER_URL" || true
